### ISSUE TITLE
'dict object' has no attribute 'Slave_IO_Running'

### ISSUE THREAD

**Issue by tarek1375** [fauust/ansible-role-mariadb#38]
Hi,
I want to create a replica that is remotly connected to a primary mariadb.
When i run the primary DB, it works like a charm.
When i run the playbook to make the replica i got this error:
```
fatal: [sql-replica]: FAILED! => 
  msg: |-
    The conditional check 'replica2.Slave_IO_Running == "No"' failed. The error was: error while evaluating conditional (replica2.Slave_IO_Running == "No"): 'dict object' has no attribute 'Slave_IO_Running'. 'dict object' has no attribute 'Slave_IO_Running'
  
    The error appears to be in '/root/.ansible/roles/fauust.mariadb/tasks/replication_replica.yml': line 47, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Start replica replication
      ^ here
```
So i checked in your role and it's realy explicit, it's this task:

```
- name: Start replica replication
  community.mysql.mysql_replication:
    mode: startreplica
    login_unix_socket: "{{ mariadb_unix_socket }}"
  when:
    - replica2.Slave_IO_Running == "No"

```
Any solution for this ?
