### ISSUE TITLE
[Question] - why is the "mariadb_data_dir" defined in roles/vars and not in roles/default ?

### ISSUE THREAD

**Issue by tarek1375** [fauust/ansible-role-mariadb#42]
Hi,
It's not really an issue but i was wondering why you defined "mariadb_data_dir" and config in the vars file of the role, is there any specifc reason ?
because with our team, we wanted to define another dir for data, but we would use group_vars or host_vars to override those variable, and in some contexts it's not really the ansible way to do it.

**Comment by fauust** [comment]
Everything that may be OS specific is defined in `vars`, that's the reason. You can override any vars in `group_vars` or `host_vars`. That's perfectly fine and it the [ansible way to do it](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence).

**Comment by BenGig** [comment]
Role vars have a high priority in the precedence list mentioned above. I did a few tests with commandline params and files in group_/host_vars, only commandline params works; and elevating the priority with `ansible.builtin.set_fact`. That's what I use now as a workaround.

Tests:
```
- hosts: mariadb-eduit-dev.ethz.ch
  roles:
    - mariadb

```
and role *mariadb" (outcome is the same as with calling fauust.mariadb directly in the playbook above):
```
- name: Dump mariadb location variable
  ansible.builtin.debug:
    var: mariadb_data_dir
- name: Apply MariaDB role
  ansible.builtin.include_role:
    name: fauust.mariadb
```

Command line variables overwrite as expected:

```
ansible-playbook -e "mariadb_data_dir=/data1/mariadb_data_cmdline" -u root -i inventory play.yml
...
TASK [mariadb : Dump mariadb location variable] **************************************************************************************************************************
ok: [mariadb-eduit-dev.ethz.ch] => {
    "mariadb_data_dir": "/data1/mariadb_data_cmdline"
}
...
TASK [fauust.mariadb : Make sure datadir and log dir exist] **************************************************************************************************************
changed: [mariadb-eduit-dev.ethz.ch] => (item=/data1/mariadb_data_cmdline)
```
Not from group_vars:
```
TASK [mariadb : Dump mariadb location variable] **************************************************************************************************************************
ok: [mariadb-eduit-dev.ethz.ch] => {
    "mariadb_data_dir": "/data1/mariadb_in_group"
}
...
TASK [fauust.mariadb : Make sure datadir and log dir exist] **************************************************************************************************************
ok: [mariadb-eduit-dev.ethz.ch] => (item=/var/lib/mysql)
```
Neither from host_vars:
```
ok: [mariadb-eduit-dev.ethz.ch] => {
    "mariadb_data_dir": "/data1/mariadb_in_host"
}
...
ok: [mariadb-eduit-dev.ethz.ch] => (item=/var/lib/mysql)
```
This addition makes it work for me:

```
- name: Set fact for mariadb_data_dir
  ansible.builtin.set_fact:
    mariadb_data_dir: "{{ mariadb_data_dir }}"

```

**Comment by fauust** [comment]
@BenGig this is not what the official documentation says, please read https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence

**Comment by BenGig** [comment]
The precedence mentioned there is:

\7. playbook group_vars/*
...
\10. playbook host_vars/*
...
\15. role vars
...
\19. set_fact

Playbook vars are defined as having lower precedence than role vars.

But I don't see an intuitive way how you could design it differently. Setting the default storage path based on the OS is important for a proper default behavior, and should suit 90% of the use cases. For the rest, set_fact does the work.

**Comment by fauust** [comment]
Oh, yes, my fault, this is the `roles/defaults` that has lower precedence. Yep, not sure how to handle this better, I'll take a moment to see if there is no better design. Thanks for the workaround, very much appreciated!

**Comment by BenGig** [comment]
Sadly there is no such thing like `include_defaults`, which would solve the problem of presetting OS dependent values in roles, and still having them overwritten easily.

Honestly, I would leave it as it is. Most of the settings are rarely changed, and for the few to be changed, a note about set_fact in the docs should be sufficient. And then advertise it as a safety measure against accidential changes of low level parameters ;-)

**Comment by atefhaloui** [comment]
Excellent role but we have no other solution that using facts :(
```
    - name: Update variables and Install packages
      block:
        # Workaround: https://github.com/fauust/ansible-role-mariadb/issues/42
        - name: Update variables
          ansible.builtin.set_fact:
            mariadb_data_dir: "{{ data_mount_path }}"
            mariadb_config_file: "/etc/mysql/mariadb.conf.d/50-server.cnf"
            mariadb_bind_address: "0.0.0.0"
            mariadb_cron_package_name: systemd-cron

        - name: Install MariaDB
          ansible.builtin.include_role:
            name: fauust.mariadb
```
